spring:
  application:
    name: RestaurantApplication
  profiles:
    active: local
app:
  name: VideoGamesApplication
  description: Spring boot application with data bas access.
info:
  title: VideoGamesApplication
  version: '@project.version@'